services:
  db:
    image: postgres:16-alpine
    container_name: items-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: items-api
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - items-net

volumes:
  db_data:

networks:
  items-net:
    driver: bridge
